language: node_js
os: linux

node_js:
  - 8

branches:
  only: master

cache:
  yarn: true
  directories:
    - "node_modules"

script:
  - yarn test --coverage --coverage-directory coverage
  - codecov
